apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana-sample
  namesapce: elastic-system
spec:
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: kibana-sample-kb-http
