apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: elastic-system
spec:
  auth:
    fileRealm:
    - secretName: my-filerealm-secret-1
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      selfSignedCertificate:
#        subjectAltNames:
#        - dns: "*.opentlc.com"
         disabled: true
  version: 7.10.0
#  image: quay.io/santander/elasticsearch:7.10.0
  nodeSets:
    - name: es-master
      config:
        node.roles: ["master"]
        node.store.allow_mmap: true
      podTemplate:
        metadata:
          labels:
            app: elasticsearch-sample
        spec:
          containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: -Xms2g -Xmx2g
              resources:
                requests:
                  memory: 4Gi # Minimo 2Gb
                  cpu: 1
                limits:
                  memory: 4Gi
                  cpu: 1
#          serviceAccountName: elasticsearch
          tolerations:
          - key: "node-role.kubernetes.io/elastic"
            effect: NoSchedule
            operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: elastic-cluster
                    operator: In
                    values:
                    - elasticsearch-sample
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2
    - name: es-data
      config:
        node.roles: ["data", "ingest"]
        node.store.allow_mmap: true
      podTemplate:
        metadata:
          labels:
            app: elasticsearch-sample
        spec:
          containers:
            - name: elasticsearch
              env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              resources:
                requests:
                  memory: 16Gi # Minimo 2Gb
                  cpu: 1
                limits:
                  memory: 16Gi
                  cpu: 1
 #         serviceAccountName: elasticsearch
          tolerations:
          - key: "node-role.kubernetes.io/elastic"
            effect: NoSchedule
            operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: elastic-cluster
                    operator: In
                    values:
                    - elasticsearch-sample
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 35Gi
            storageClassName: gp2
  transport:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
  updateStrategy:
    changeBudget: {}
