apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: elastic-system
spec:
  auth: {}
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate: {}
  nodeSets:
    - config:
        node.data: true
        node.ingest: true
        node.master: true
        node.store.allow_mmap: false
      podTemplate:
       metadata:
         labels:
           app: elasticsearch-sample 
       spec:
         containers:
           - name: elasticsearch
             resources:
               requests:
                 memory: 8Gi
                 cpu: 1
               limits:
                 memory: 8Gi
                 cpu: 2
      count: 3
      name: default
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: gp2
  transport:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
  updateStrategy:
    changeBudget: {}
  version: 7.9.3
