apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: elastic-system
  labels:
    app: elasticsearch-sample
  annotations:
    description: "SA para ejecutar los pods de ElasticSearch"
