apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: elastic-system
spec:
  version: 7.10.0
  count: 2
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
      nodeSelector:
        elastic-cluster: elasticsearch-sample
      tolerations:
        - key: "node-role.kubernetes.io/elastic"
          effect: NoSchedule
          operator: Exists
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1
