apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: elastic
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,elastic]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/elastic: ""
